baseURL = "https://onceihadacat.com/"
languageCode = "en-us"
title = "once I had a ðŸˆ"
theme = "oihac"

contentDir = "content"

googleAnalytics = "UA-139965074-1"

# Highlighting config (Pygments)

# Styles created with hugo gen chromastyles --style=perldoc > assets/stylesheets/_syntax-chroma.css
pygmentsUseClasses =  true
pygmentsCodeFences = true
disableHugoGeneratorInject = true

# Use the new and fast Chroma highlighter (Pygments port) in Hugo >= 0.28.
pygmentsUseClassic = false

# See https://help.farbox.com/pygments.html
# Also see pygmentsUseClasses above.
pygmentsStyle = "perldoc"

disqusShortname="linode-1"

#disableKinds = ["taxonomy", "taxonomyTerm"]

rssLimit = 30

enableGitInfo = true

[frontmatter]
lastmod = [":git", "lastmod", "date", "publishDate"]

[blackfriday]
fractions = false

# [outputFormats.Algolia]
# baseName = "algolia"
# isPlainText = true
# mediaType = "application/json"
# notAlternative = true

# [params.algolia]
# vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
# params = ["keywords", "description", "title_short"]

[outputs]
home = [ "HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]

[taxonomies]
audience = "audiences"
concentration = "concentrations"
language = "languages"

[params]
description = "Tinkering around with musical things. Stumbling into synthesizer and other musical software."
default_image_width = 120
default_image_height = 120

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_default = "Mon Jan 2 2006"

# Related Content ("See Also") configuration.
# [related]
# threshold = 80
# includeNewer = true
# toLower = false
#
# [[related.indices]]
# name = "keywords"
# weight = 100
# [[related.indices]]
# name  = "date"
# weight = 10
# pattern = "2006"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1